### ISSUE TITLE
bug using options.boundary with options.shifts_method = 'cubic'

### ISSUE THREAD

**Issue by dpacheco0921** [flatironinstitute/NoRMCorre#13]
Hi Eftychios

When using the options.shifts_method = 'cubic', the imwarp function by default set to zero all values outside the image. So options.boundary does not have an effect on this, however you can fix that if you add the imwarp(*, *, 'FillValues', add_value).

one could easily fix this on apply_shifts.m by adding:
            add_value = 0;
            if strcmpi(options.boundary, 'nan')
                add_value = nan;
            end
on line: 213
and editing imwarp to accept 'FillValues' as add_value.
This would only work if you want those values to be 0 or nan, but dont quite know how to get the options.boundary options: 'copy' and 'template' implemented.

Diego

**Comment by epnev** [comment]
Hi @dpacheco0921 
Thanks for bringing this into my attention. I followed your suggestion, by setting the boundaries to NaN if that's the option.boundary and to the min value if not. As you said, there is no straightforward way to put the two other options.
