### ISSUE TITLE
An error appeared when NoRMCorre ran on Matlab.

### ISSUE THREAD

**Issue by puredragonzcl** [flatironinstitute/NoRMCorre#16]
In NoRMCorre,when I selected a local tif file(transformed by a bmp file),an error appeared on function imwarp:
错误使用 imwarp
需要的 tform 应为以下类型之一:

images.geotrans.internal.GeometricTransformation

但其类型是 double。Meaning that I use the imwrap incorrectly,the tform should be this type:images.geotrans.internal.GeometricTransformation.But actually it was double.

I don't konw how to solve this problem,so ask for help and reply.Thank you!

**Comment by epnev** [comment]
I can't be sure what the problem is here. Does the code run if you set 
` options.correct_bidir = false ` ? This will bypass the usage of imwarp

**Comment by puredragonzcl** [comment]
The problem has been solved.The code can be run on matlab2017.Primarily I used the 2014 version.Thanks for your reply！
