### ISSUE TITLE
python implementation

### ISSUE THREAD

**Issue by bendichter** [flatironinstitute/NoRMCorre#27]
Hey all,

I am planning on starting a python implementation of this package [here](https://github.com/bendichter/NoRMCorre-python). Let me know if you would like to contribute!

**Comment by bendichter** [comment]
I am also open to changing the location of this repo for better cohesiveness of the calcium imaging processing pipeline tools.

**Comment by epnev** [comment]
@bendichter Even though there is no consistency with respect to function names and notation, most  of NoRMCorre's functionality is present in the [motion correction module](https://github.com/flatironinstitute/CaImAn/blob/master/caiman/motion_correction.py) of CaImAn, so it would be good to avoid replicating this. We can talk about what you want to do and what is missing.

**Comment by bendichter** [comment]
@epnev OK that sounds good. Essentially we need to NoRMCorre algorithm to work for 3D data. Is that currently possible using the motion correction module?

**Comment by epnev** [comment]
@bendichter No, that's not currently possible. I'm closing this issue and will open a new one in the CaImAn repo to outline what is there already and what needs to be done.

**Comment by bendichter** [comment]
Sounds good, thanks @epnev!
