### ISSUE TITLE
sizY not specified when loading a tiff via filename

### ISSUE THREAD

**Issue by Enakcihc** [flatironinstitute/NoRMCorre#3]
I was trying to run NoRMCorre with the filename of a tiff as the input argument Y. 
` [M1,shifts1,template1] = normcorre(name,options_rigid)` 

turns out it grabs the info for the tiff (lines 24-26 of normcorre)
`       tiffInfo = imfinfo(Y);`
`        filetype = 'tif';`
 `       T = length(tiffInfo);`
but did not specify the variable sizY and ran into an error at line 49 of normcorre
`nd = length(sizY)-1;                          % determine whether imaging is 2d or 3d`

**Comment by epnev** [comment]
Hi @Enakcihc 
Thanks for catching this! The bug is fixed now.
