### ISSUE TITLE
how do i save the corrected tiff stack image?

### ISSUE THREAD

**Issue by m0userat25** [flatironinstitute/NoRMCorre#4]
i am sorry if this is a dumb question but i can't figure out how to save the non rigid corrected tiff stack.

**Comment by epnev** [comment]
@m0userat25 At the moment, the only way you can do this is by first running normcorre/normcorre_batch, and then saving the output as .tiff file using  the ```saveastiff``` command.

**Comment by epnev** [comment]
```normcorre_batch``` can now output the registered 2D data as a tiff stack, by choosing ```options.output_type = 'tif'```. The name of the output file can be specified from ```options.tiff_filename```
