### ISSUE TITLE
bug in normcorre.m when using 3D data

### ISSUE THREAD

**Issue by dpacheco0921** [flatironinstitute/NoRMCorre#7]
When using the cubic shift_method, I get this error:

Error using imwarp>checkImageAgreementWithTform (line 269)
The number of dimensions of the input image A must be 3 when the specified geometric transformation is 3-D.

for dm = 1:3; shifts_up(:,:,:,dm) = imwarp(shifts_temp(:,:,:,dm),tform,'OutputView',imref3d([options.d1,options.d2,options.d3])); end

* the size of shifts_temp(:,:,:,dm) is actually 1, but tform is three-dimensional.

Also there is a bug in line 306:
- buffer{i,j,k}(:,:,ind) = Mt2{ii};
+ if nd == 2; buffer{i,j,k}(:,:,ind) = Mt2{ii}; end
+  if nd == 3; buffer{i,j,k}(:,:,:,ind) = Mt2{ii}; end

**Comment by epnev** [comment]
@dpacheco0921 Thanks for bringing this to my attention. I think the bug should be fixed now.
