### ISSUE TITLE
Image registration progress on command line

### ISSUE THREAD

**Issue by ehennestad** [flatironinstitute/NoRMCorre#8]
Hi,

I think it is great to have the progress printed to the command line, but it results in a lot of text, and sometimes I want to see messages printed before I started image registration.

I have some few pieces of code that I use in my scripts to update the the textstring on the command line, instead of printing a new one:

```
str=[num2str(n), 'out of ', num2str(nFrames), 'frames registered'];
refreshdisp(str, prevstr, n);
prevstr=str; 
```

where refreshdisp looks like this:

```
function refreshdisp(str,prevstr,iteration)

if ~exist('iteration')
    iteration=2;
end

if iteration==1
    fprintf(str)
else
    fprintf(char(8*ones(1,length(prevstr))));
    fprintf(str);
end
```

also need to initialize prevstr.

Maybe this could be added to normcorre?

**Comment by epnev** [comment]
Thank for the suggestion, I incorporated it!
